### ISSUE TITLE
这又是个啥？

### ISSUE THREAD

**Issue by paomian** [sdutlinux/slug#1]

**Comment by lidashuang** [comment]
没想好搞什么

**Comment by paomian** [comment]
凑

**Comment by zhwei** [comment]
凑

**Comment by lidashuang** [comment]
@zhwei 写个论坛吧，学习Elixir用，登录我已经做好了

**Comment by zhwei** [comment]
论坛泛滥了。。。

**Comment by paomian** [comment]
@zhwei 我想用clojure重写你那个gotit。。。。

**Comment by paomian** [comment]
@lidashuang 你看怎么样，重写gotit

**Comment by lidashuang** [comment]
@paomian 写写写

**Comment by zhwei** [comment]
@paomian 要写就写全套的好不， gotit太简单了， 没啥功能， 做个抓取平台把。

**Comment by lidashuang** [comment]
@zhwei 开个头啊

**Comment by zhwei** [comment]
@paomian @lidashuang 用什么写？

**Comment by lidashuang** [comment]
@zhwei 没意见，不要用php

**Comment by zhwei** [comment]
擦，你觉得会用么，再说PHP根本就是不是干这个的。。。

**Comment by Ma233** [comment]
身为世界上最好的语言，PHP什么不能干？

**Comment by zhwei** [comment]
没有最好的语言只有最合适的语言。

**Comment by paomian** [comment]
clojure！

**Comment by zhwei** [comment]
作，从没用过。。。

**Comment by paomian** [comment]
@zhwei 学啊，clojure写着很爽的

**Comment by lidashuang** [comment]
@paomian 宏怎么搞代码热更

**Comment by paomian** [comment]
@lidashuang 这个表达不是很准确，有时间给你们讲详细细节

**Comment by zhwei** [comment]
求指导

**Comment by zhwei** [comment]
请用Clojure打动我

**Comment by Ma233** [comment]
请用Clojure打我

**Comment by paomian** [comment]
@zhwei 你们写写就知道了，请看这里 [clj-diamond](https://github.com/leancloud/clj-diamond)
